#
# Autogenerated by Thrift Compiler (0.14.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module Bush
  class UserInfo; end

  class RcpResponse; end

  class TraceContext; end

  class UserInfo
    include ::Thrift::Struct, ::Thrift::Struct_Union
    ID = 1
    NAME = 2

    FIELDS = {
      ID => {:type => ::Thrift::Types::I32, :name => 'id'},
      NAME => {:type => ::Thrift::Types::STRING, :name => 'name'}
    }

    def struct_fields; FIELDS; end

    def validate
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field id is unset!') unless @id
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field name is unset!') unless @name
    end

    ::Thrift::Struct.generate_accessors self
  end

  class RcpResponse
    include ::Thrift::Struct, ::Thrift::Struct_Union
    CODE = 1
    USERINFO = 2

    FIELDS = {
      CODE => {:type => ::Thrift::Types::I32, :name => 'code'},
      USERINFO => {:type => ::Thrift::Types::STRUCT, :name => 'userInfo', :class => ::Bush::UserInfo}
    }

    def struct_fields; FIELDS; end

    def validate
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field code is unset!') unless @code
    end

    ::Thrift::Struct.generate_accessors self
  end

  class TraceContext
    include ::Thrift::Struct, ::Thrift::Struct_Union
    CARRIER = 1

    FIELDS = {
      CARRIER => {:type => ::Thrift::Types::STRING, :name => 'carrier'}
    }

    def struct_fields; FIELDS; end

    def validate
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field carrier is unset!') unless @carrier
    end

    ::Thrift::Struct.generate_accessors self
  end

end
